# Trigger: apps/web/** changes only
substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _IMAGE: "deniko-web"
  _SERVICE: "deniko-web"

steps:
  # Build Web
  - id: "Build Web"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "apps/web/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."

  # Push Web image
  - id: "Push Web"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build Web"]
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}"

  # Deploy Web service
  - id: "Deploy Web"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push Web"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: "1800s"
