substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _API_IMAGE: "deniko-api"
  _WEB_IMAGE: "deniko-web"

steps:
  - id: "Build API"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "apps/api/Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest",
        ".",
      ]

  - id: "Build Web"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    args:
      [
        "build",
        "-f",
        "apps/web/Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest",
        ".",
      ]

  - id: "Push API ($BUILD_ID)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID",
      ]

  - id: "Push API (latest)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest",
      ]

  - id: "Push Web ($BUILD_ID)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build Web"]
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID",
      ]

  - id: "Push Web (latest)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build Web"]
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest",
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1800s"
