substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _API_IMAGE: "deniko-api"
  _WEB_IMAGE: "deniko-web"
  _API_SERVICE: "deniko-api"
  _WEB_SERVICE: "deniko-web"
  _MIGRATE_JOB: "deniko-db-migrate"

  # Runtime service accounts (sende mevcut)
  _API_SA: "deniko-api-sa@deniko.iam.gserviceaccount.com"
  _WEB_SA: "deniko-web-sa@deniko.iam.gserviceaccount.com"

  # Secret names (value yazmıyoruz)
  _DB_SECRET: "DATABASE_URL"
  _DIRECT_DB_SECRET: "DIRECT_URL"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitution_option: ALLOW_LOOSE

timeout: "1800s"

steps:
  # Build API and Web in parallel
  - id: "Build API"
    name: "gcr.io/cloud-builders/docker"
    env: ["DOCKER_BUILDKIT=1"]
    args:
      - "build"
      - "-f"
      - "apps/api/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."

  - id: "Build Web"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["-"]
    env: ["DOCKER_BUILDKIT=1"]
    args:
      - "build"
      - "-f"
      - "apps/web/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."

  # Push images
  - id: "Push API"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}"

  - id: "Push Web"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build Web"]
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}"

  # Deploy & execute database migration job (after API image pushed)
  - id: "Deploy migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push API"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "--service-account"
      - "${_API_SA}"
      - "--set-secrets"
      - "DATABASE_URL=${_DB_SECRET}:latest,DIRECT_URL=${_DIRECT_DB_SECRET}:latest"
      - "--command"
      - "/app/node_modules/.bin/prisma"
      - "--args"
      - "migrate,deploy,--schema,./packages/db/prisma/schema.prisma"
      - "--max-retries"
      - "0"
      - "--task-timeout"
      - "30m"
      - "--command"
      - "/app/node_modules/.bin/prisma"
      - "--args"
      - "migrate,deploy,--schema,./prisma/schema.prisma"
      - "--quiet"

  - id: "Execute migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Deploy migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "execute"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--wait"
      - "--quiet"

  # Deploy services after migration
  - id: "Deploy API"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Execute migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_API_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "--service-account"
      - "${_API_SA}"
      - "--quiet"

  - id: "Deploy Web"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push Web", "Execute migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_WEB_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID"
      - "--service-account"
      - "${_WEB_SA}"
      - "--quiet"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_WEB_IMAGE}:latest"
