steps:
  # -------------------------------------------------------------------------
  # 1. Build API
  # -------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-api:latest",
        "-f",
        "apps/api/Dockerfile",
        ".",
      ]
    id: "Build API"

  # -------------------------------------------------------------------------
  # 2. Build Web
  # -------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-web:latest",
        "-f",
        "apps/web/Dockerfile",
        ".",
      ]
    id: "Build Web"
    waitFor: ["-"] # Run in parallel with API build

  # -------------------------------------------------------------------------
  # 3. Push API
  # -------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-api:latest",
      ]
    id: "Push API"
    waitFor: ["Build API"]

  # -------------------------------------------------------------------------
  # 4. Push Web
  # -------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-web:latest",
      ]
    id: "Push Web"
    waitFor: ["Build Web"]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-api:latest"
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/deniko/deniko-web:latest"

options:
  logging: CLOUD_LOGGING_ONLY
