substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _IMAGE: "deniko-api"
  _SERVICE: "deniko-api"
  _MIGRATE_JOB: "deniko-db-migrate"

steps:
  - id: "Build API"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "apps/api/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"
      - "."

  - id: "Push API ($BUILD_ID)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"

  - id: "Push API (latest)"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"

  # --- DB migrations: job image update + execute ---
  - id: "Update migrate job image"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push API ($BUILD_ID)"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"

  - id: "Execute migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Update migrate job image"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "execute"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--wait"

  # --- Deploy API service after successful migrations ---
  - id: "Deploy API"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Execute migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
