substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _IMAGE: "deniko-api"

steps:
  - id: "Build API"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "apps/api/Dockerfile",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest",
        ".",
      ]

  - id: "Push API ($BUILD_ID)"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID",
      ]

  - id: "Push API (latest)"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest",
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"
