# Trigger: apps/api/** changes only
substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "deniko"
  _API_IMAGE: "deniko-api"
  _API_SERVICE: "deniko-api"
  _MIGRATE_JOB: "deniko-db-migrate"
  _API_SA: "deniko-api-sa@deniko.iam.gserviceaccount.com"
  _DB_SECRET: "DATABASE_URL"
  _DIRECT_DB_SECRET: "DIRECT_URL"

steps:
  # Build API
  - id: "Build API"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "apps/api/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."

  # Push API image
  - id: "Push API"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build API"]
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}"

  # Deploy migration job
  - id: "Deploy migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Push API"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "--service-account"
      - "${_API_SA}"
      - "--set-secrets"
      - "DATABASE_URL=${_DB_SECRET}:latest,DIRECT_URL=${_DIRECT_DB_SECRET}:latest"
      - "--command"
      - "/app/node_modules/.bin/prisma"
      - "--args"
      - "migrate,deploy,--schema,./packages/db/prisma/schema.prisma"
      - "--max-retries"
      - "0"
      - "--task-timeout"
      - "30m"
      - "--quiet"

  # Run migration
  - id: "Execute migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Deploy migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "execute"
      - "${_MIGRATE_JOB}"
      - "--region"
      - "${_REGION}"
      - "--wait"

  # Deploy API service
  - id: "Deploy API"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    waitFor: ["Execute migrate job"]
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_API_SERVICE}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
      - "--service-account"
      - "${_API_SA}"
      - "--quiet"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_IMAGE}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: "1800s"
